kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: eap-app-build-artifacts
  annotations:
    openshift.io/generated-by: OpenShiftNewApp3
  labels:
    app: eap74-openjdk11-basic-s2i
    application: eap-app
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'eap-app-build-artifacts:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'jboss-eap74-openjdk11-openshift:7.4.0'
      env:
        - name: MAVEN_MIRROR_URL
        - name: MAVEN_ARGS_APPEND
          value: '-Dcom.redhat.xpaas.repo.jbossorg'
        - name: GALLEON_PROVISION_DEFAULT_FAT_SERVER
          value: 'true'
        - name: ARTIFACT_DIR
      incremental: true
      forcePull: true
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/deewhyweb/eap-quickstarts.git'
      ref: 7.4.x
    contextDir: kitchensink
  triggers:
    - type: ConfigChange
  runPolicy: Serial