apiVersion: wildfly.org/v1alpha1
kind: WildFlyServer
metadata:
  name: kitchen-sink
spec:
  applicationImage: 'kitchensink:latest'
  envFrom:
    - configMapRef:
        name: eap-config
  replicas: 1