kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: eap-app
  labels:
    application: eap-app
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'eap-app:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'jboss-eap74-openjdk11-runtime-openshift:7.4.0'
      imageOptimizationPolicy: SkipLayers
  postCommit: {}
  source:
    type: Dockerfile
    dockerfile: |-
      FROM jboss-eap74-openjdk11-runtime-openshift:7.4.0
      COPY /server $JBOSS_HOME
      USER root
      RUN chown -R jboss:root $JBOSS_HOME && chmod -R ug+rwX $JBOSS_HOME
      USER jboss
      CMD $JBOSS_HOME/bin/openshift-launch.sh
    images:
      - from:
          kind: ImageStreamTag
          name: 'eap-app-build-artifacts:latest'
        paths:
          - sourcePath: /s2i-output/server/
            destinationDir: .
  triggers:
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: 'eap-app-build-artifacts:latest'
    - type: ConfigChange
  runPolicy: Serial
