apiVersion: wildfly.org/v1alpha1
kind: WildFlyServer
metadata:
  name: kitchen-sink
spec:
  applicationImage: 'image-registry.openshift-image-registry.svc:5000/eap/eap74:latest'
  envFrom:
    - configMapRef:
        name: eap-config
  replicas: 1