apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: eap-app-template
spec:
  params:
  - name: git-repo-url
    description: The git repository url
  - name: git-revision
    description: The git revision
    default: pipelines-1.8
  - name: git-repo-name
    description: The name of the deployment to be created / patched

  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: build-deploy-$(tt.params.git-repo-name)-
    spec:
      params:
        - name: repo-url
          value: 'https://github.com/deewhyweb/eap-quickstarts.git'
        - name: revision
          value: 7.4.x
        - name: context-path
          value: kitchensink
      pipelineRef:
        name: maven-pipeline
      serviceAccountName: pipeline
      timeout: 1h0m0s
      workspaces:
        - name: shared-workspace
          persistentVolumeClaim:
            claimName: tekton
        - emptyDir: {}
          name: maven-settings